[2025-03-18T23:05:14.989+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-18T23:05:14.996+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-18T23:04:00+00:00 [queued]>
[2025-03-18T23:05:14.999+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-18T23:04:00+00:00 [queued]>
[2025-03-18T23:05:14.999+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-18T23:05:15.004+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): check_raw_data_file> on 2025-03-18 23:04:00+00:00
[2025-03-18T23:05:15.010+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7032) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-18T23:05:15.012+0000] {standard_task_runner.py:72} INFO - Started process 7033 to run task
[2025-03-18T23:05:15.010+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bike_rental_pipeline', 'check_raw_data_file', 'scheduled__2025-03-18T23:04:00+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/data_pipline_true.py', '--cfg-path', '/tmp/tmpve3a5aab']
[2025-03-18T23:05:15.012+0000] {standard_task_runner.py:105} INFO - Job 339: Subtask check_raw_data_file
[2025-03-18T23:05:15.038+0000] {task_command.py:467} INFO - Running <TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-18T23:04:00+00:00 [running]> on host 5360daad3715
[2025-03-18T23:05:15.077+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bike_rental_pipeline' AIRFLOW_CTX_TASK_ID='check_raw_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-18T23:04:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-18T23:04:00+00:00'
[2025-03-18T23:05:15.078+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-18T23:05:15.085+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-03-18T23:05:15.089+0000] {base.py:84} INFO - Retrieving connection 'bike_rental_data'
[2025-03-18T23:05:15.089+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/data/day.csv
[2025-03-18T23:05:15.090+0000] {filesystem.py:113} INFO - Found File /opt/***/dags/data/day.csv last modified: 20220422002206
[2025-03-18T23:05:15.090+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-03-18T23:05:15.090+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/data/day.csv
[2025-03-18T23:05:15.090+0000] {filesystem.py:113} INFO - Found File /opt/***/dags/data/day.csv last modified: 20220422002206
[2025-03-18T23:05:15.094+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-18T23:05:15.094+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bike_rental_pipeline, task_id=check_raw_data_file, run_id=scheduled__2025-03-18T23:04:00+00:00, execution_date=20250318T230400, start_date=20250318T230514, end_date=20250318T230515
[2025-03-18T23:05:15.116+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-18T23:05:15.134+0000] {taskinstance.py:3901} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2025-03-18T23:05:15.135+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
