[2025-03-20T12:40:00.603+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T12:40:00.610+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-20T12:39:00+00:00 [queued]>
[2025-03-20T12:40:00.614+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-20T12:39:00+00:00 [queued]>
[2025-03-20T12:40:00.614+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-20T12:40:00.619+0000] {taskinstance.py:2890} INFO - Executing <Task(FileSensor): check_raw_data_file> on 2025-03-20 12:39:00+00:00
[2025-03-20T12:40:00.624+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=980) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-20T12:40:00.624+0000] {standard_task_runner.py:72} INFO - Started process 981 to run task
[2025-03-20T12:40:00.624+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bike_rental_pipeline', 'check_raw_data_file', 'scheduled__2025-03-20T12:39:00+00:00', '--job-id', '645', '--raw', '--subdir', 'DAGS_FOLDER/data_pipline_true.py', '--cfg-path', '/tmp/tmp7nihotqr']
[2025-03-20T12:40:00.626+0000] {standard_task_runner.py:105} INFO - Job 645: Subtask check_raw_data_file
[2025-03-20T12:40:00.649+0000] {task_command.py:467} INFO - Running <TaskInstance: bike_rental_pipeline.check_raw_data_file scheduled__2025-03-20T12:39:00+00:00 [running]> on host fd61bea7cb7a
[2025-03-20T12:40:00.688+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bike_rental_pipeline' AIRFLOW_CTX_TASK_ID='check_raw_data_file' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T12:39:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T12:39:00+00:00'
[2025-03-20T12:40:00.688+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T12:40:00.695+0000] {baseoperator.py:423} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2025-03-20T12:40:00.700+0000] {base.py:84} INFO - Retrieving connection 'bike_rental_data'
[2025-03-20T12:40:00.700+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/data/day.csv
[2025-03-20T12:40:00.700+0000] {filesystem.py:113} INFO - Found File /opt/***/dags/data/day.csv last modified: 20220422002206
[2025-03-20T12:40:00.700+0000] {base.py:339} INFO - Success criteria met. Exiting.
[2025-03-20T12:40:00.700+0000] {filesystem.py:109} INFO - Poking for file /opt/***/dags/data/day.csv
[2025-03-20T12:40:00.700+0000] {filesystem.py:113} INFO - Found File /opt/***/dags/data/day.csv last modified: 20220422002206
[2025-03-20T12:40:00.704+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T12:40:00.705+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=bike_rental_pipeline, task_id=check_raw_data_file, run_id=scheduled__2025-03-20T12:39:00+00:00, execution_date=20250320T123900, start_date=20250320T124000, end_date=20250320T124000
[2025-03-20T12:40:00.727+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T12:40:00.742+0000] {taskinstance.py:3901} INFO - 6 downstream tasks scheduled from follow-on schedule check
[2025-03-20T12:40:00.743+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
