[2025-04-08T21:10:23.437+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:10:23.477+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_wind_speed_table scheduled__2025-04-08T21:09:00+00:00 [queued]>
[2025-04-08T21:10:23.488+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_wind_speed_table scheduled__2025-04-08T21:09:00+00:00 [queued]>
[2025-04-08T21:10:23.492+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:10:23.546+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_wind_speed_table> on 2025-04-08 21:09:00+00:00
[2025-04-08T21:10:23.557+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20086) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:10:23.559+0000] {standard_task_runner.py:72} INFO - Started process 20111 to run task
[2025-04-08T21:10:23.557+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_dim_wind_speed_table', 'scheduled__2025-04-08T21:09:00+00:00', '--job-id', '884', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmprabaiume']
[2025-04-08T21:10:23.568+0000] {standard_task_runner.py:105} INFO - Job 884: Subtask create_dim_wind_speed_table
[2025-04-08T21:10:23.705+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_dim_wind_speed_table scheduled__2025-04-08T21:09:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:10:23.781+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_dim_wind_speed_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:09:00+00:00'
[2025-04-08T21:10:23.782+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:10:23.797+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:10:23.811+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:10:23.819+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:10:23.820+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_dim_wind_speed_table, run_id=scheduled__2025-04-08T21:09:00+00:00, execution_date=20250408T210900, start_date=20250408T211023, end_date=20250408T211023
[2025-04-08T21:10:23.868+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:10:23.890+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T21:10:23.892+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
