[2025-04-08T21:27:12.763+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:27:12.783+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_temp_table scheduled__2025-04-08T21:26:00+00:00 [queued]>
[2025-04-08T21:27:12.791+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.create_dim_temp_table scheduled__2025-04-08T21:26:00+00:00 [queued]>
[2025-04-08T21:27:12.792+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:27:12.806+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_dim_temp_table> on 2025-04-08 21:26:00+00:00
[2025-04-08T21:27:12.818+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_dim_temp_table', 'scheduled__2025-04-08T21:26:00+00:00', '--job-id', '946', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmp6mgt_3aj']
[2025-04-08T21:27:12.821+0000] {standard_task_runner.py:105} INFO - Job 946: Subtask create_dim_temp_table
[2025-04-08T21:27:12.826+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=21801) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:27:12.827+0000] {standard_task_runner.py:72} INFO - Started process 21803 to run task
[2025-04-08T21:27:12.883+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.create_dim_temp_table scheduled__2025-04-08T21:26:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:27:12.945+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='create_dim_temp_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:26:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:26:00+00:00'
[2025-04-08T21:27:12.946+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:27:12.962+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:27:12.974+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:27:12.985+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:27:12.986+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_dim_temp_table, run_id=scheduled__2025-04-08T21:26:00+00:00, execution_date=20250408T212600, start_date=20250408T212712, end_date=20250408T212712
[2025-04-08T21:27:13.019+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:27:13.029+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
